name: Azure Connection Test (OIDC)

on:
  workflow_dispatch:    # Manual trigger
  pull_request:         # Trigger on PR events

permissions:
  id-token: write       # Required for OIDC authentication
  contents: read        # Optional, for accessing repo contents

jobs:
  test-azure-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: OIDC
      - name: Test Azure CLI
        run: |
          az account show
          az group list --output table
